version: "3.9"
services:
  worker:
    build: .
    container_name: news-worker
    working_dir: /app
    env_file:
      - app/.env         # <- 지금 .env가 app/ 안에 있으니 이렇게 참조 (비공유가 좋으면 밖으로 빼도 OK)
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "ps -o pid= -C python | grep -q ."]
      interval: 30s
      timeout: 5s
      retries: 3
    stop_grace_period: 20s

  redis:
    image: redis:7-alpine
    container_name: news-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
